version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql_macvlan
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
    networks:
      nginx-reverse-proxy_macvlan_net:
        ipv4_address: 10.0.10.201

  mysql-backup:
    image: fradelg/mysql-cron-backup
    container_name: mysql_macvlan_backup
    restart: unless-stopped
    environment:
      MYSQL_HOST: 10.0.10.201        # IP-adressen på db-containeren
      MYSQL_USER: root
      MYSQL_PASS: rootpass
      MYSQL_PORT: 3306
      CRON_TIME: "*/5 * * * *"       # Her hvert 5. minut til test
      MAX_BACKUPS: 7
      INIT_BACKUP: "true"            # Laver backup straks ved container-start
      GZIP_LEVEL: 9
    networks:
      nginx-reverse-proxy_macvlan_net:
        ipv4_address: 10.0.10.202    # Ledig IP i samme subnet
    volumes:
      - ./backups:/backup            # Mapper til lokal mappe for backupfiler

networks:
  nginx-reverse-proxy_macvlan_net:
    external: true
