all:
  children:
    cisco_routers:
      hosts:
        Router-1:
          ansible_host: 192.168.8.172
          router_hostname: Router-1
        Router-2:
          ansible_host: 192.168.8.173
          router_hostname: Router-2
        Router-3:
          ansible_host: 192.168.8.174
          router_hostname: Router-3
      vars:
        ansible_connection: network_cli
        ansible_network_os: cisco.ios.ios
        ansible_user: administrator
        ansible_password: Password1
        ansible_become: yes
        ansible_become_method: enable
        ansible_become_password: Password1