version: '3'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./web1:/usr/share/nginx/html/web1:ro
      - ./web2:/usr/share/nginx/html/web2:ro
      - ./web3:/usr/share/nginx/html/web3:ro
