version: "3.9" 
 
services: 
  nginx: 
    image: nginx:latest 
    container_name: nginx_macvlan 
    networks: 
      nginx-reverse-proxy_macvlan_net: 
        ipv4_address: 10.0.10.200 
    # Tilg책s direkte p책 http://192.168.1.200 
 
  db: 
    image: mysql:8.0 
    container_name: mysql_macvlan 
    environment: 
      MYSQL_ROOT_PASSWORD: rootpass 
      MYSQL_DATABASE: testdb 
    networks: 
      nginx-reverse-proxy_macvlan_net: 
        ipv4_address: 10.0.10.201 
    # Tilg책s direkte p책 192.168.1.201:3306 
 
networks: 
  nginx-reverse-proxy_macvlan_net: 
    external: true